services:
  app:
    container_name: felipecavalca_dev
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "20080:80"
    volumes:
      - ./app:/usr/local/apache2/htdocs/
