services:
  app:
    container_name: felipecavalca_dev_app
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "20080:80"
    volumes:
      - ./app:/usr/local/apache2/htdocs/
      - ./docs:/usr/local/apache2/htdocs/docs
    networks:
      - felipecavalca-network

  api:
    container_name: felipecavalca_dev_api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    env_file:
      - ./api/.env
    volumes:
      - ./api:/var/www/html
      - felipecavalca_storage:/storage
    networks:
      - felipecavalca-network
    depends_on:
      - redis

  redis:
    container_name: felipecavalca_dev_redis
    image: redis:latest
    volumes:
      - felipecavalca-redis_data:/data
    networks:
      - felipecavalca-network

volumes:
  felipecavalca_storage:
    name: felipecavalca_storage
    labels:
      com.description: "This volume is used for data storage"
  felipecavalca-redis_data:
    name: felipecavalca-redis_data
    labels:
      com.description: "This volume is used for Redis"

networks:
  felipecavalca-network:
    name: felipecavalca-network
