services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "20080:80"
      - "20443:443"
    volumes:
      - ./app:/usr/local/apache2/htdocs/
